# Generated by Django 3.0.14 on 2023-03-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relogioponto.Funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relogioponto.Funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField()),
                ('saida', models.DateTimeField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data', models.DateField()),
                ('saldo_diario', models.DecimalField(decimal_places=2, max_digits=4)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relogioponto.Funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('horas_extras', models.DecimalField(decimal_places=2, max_digits=4)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relogioponto.Funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relogioponto.Funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relogioponto.Funcionarios')),
            ],
        ),
    ]
