# Generated by Django 3.0.14 on 2023-03-29 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relogioponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='cargo',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$')]),
        ),
    ]
